### ISSUE TITLE
undefined reference to `H2R_HSBtoRGBfloat(float, float, float, int*)

### ISSUE THREAD

**Issue by petermoffat** [julioterra/HSB_Color#3]
Does not compile in Arduino IDE 1.6.10 with this error.
